session_name: prod db
windows:
- window_name: prod db do
  layout: tiled
  panes:
    - bash /home/hypen9/Documents/code/tasking/.tasknotes.d/snippets/vlxwXCjeNL9.snip
    - shell_command:
        - sleep 4
        - bash /home/hypen9/Documents/code/tasking/.tasknotes.d/snippets/1kkD0drHQD5.snip
