#!/bin/bash
# elvis: english		-- Search Stack Overflow
# Author: jason ryan • http://jasonwryan.com + hypen9

# /home/hypen9/.config/surfraw/elvi/english
. surfraw || exit 1

w3_config_hook () {
def   SURFRAW_stack_categories  "$SURFRAW_categories"
def   SURFRAW_stack_unix         0
def   SURFRAW_stack_results      25
}

w3_usage_hook () {
    cat <<EOF

Usage: $w3_argv0 [options] [search-string]
Description:
 Search Stack Overflow (http://stackoverflow.com)
 Combine search terms (tags) with a "+" eg., "bash+script"

Local options:
 -sort=CATEGORIES
 -s=CATEGORIES
          new           |   Most recently asked (default)
          feat          |   Questions with open bounties
          vote          |   Questions with most votes
          active        |   Recently active
          null          |   No upvoted answers
          faq           |   Questions with the most links
                            Default: new

 -u                     |   Search Unix & Linux Exchange
                            Default: no

 -num=NUMBER            |   Number of results per page
                            Default: $SURFRAW_stack_results

EOF
    w3_global_usage
}

w3_parse_option_hook () {
    opt="$1"
    optarg="$2"
    case "$opt" in
	-sort=*)    setopt   SURFRAW_stack_categories   $optarg ;;
	-s=*)       setopt   SURFRAW_stack_categories   $optarg ;;
	-num=*)     setopt   SURFRAW_stack_results      $optarg ;;
	-u)         setoptyn SURFRAW_stack_unix         1       ;;
	*) return 1 ;;
    esac
    return 0
}
w3_config
w3_parse_args "$@"
# w3_args now contains list of arguments
case "$SURFRAW_stack_categories" in
	new)    category="newest"     	;;
	feat)   category="featured"   	;;
	vote)   category="votes"      	;;
	active) category="active"     	;;
	null)   category="unanswered" 	;;
	faq)    category="faq"        	;;
	*)      category="newest"     	;;
esac

# Check for Unix & Linux Exchange
if [ "$SURFRAW_stack_unix" = 1 ]; then
	url="http://unix.stackexchange.com"
else
	url="https://english.stackexchange.com"
fi

# No arguments passed
if [ -z "$w3_args" ]; then
    w3_browse_url "$url"
else
    i=0
    read -r -a array <<< "$w3_args"
    args=""
    for element in "${array[@]}"

    do
        current_arg=""
        # echo "$element"
        if expr match "$element" '\+' > /dev/null;
        then
            suffix=${element:1}
            current_arg="[$suffix]"
        else
            suffix=$element
            current_arg="$suffix"
        fi

        if [ $i -gt 0 ];
        then
            current_arg="+$current_arg"
        fi
        ((i++))

        # echo $current_arg
        args="$args$current_arg"
    done
    echo $args
    # escaped_args=$(w3_url_of_arg $args)
	if [ -n "$SURFRAW_stack_categories" ]; then
	    w3_browse_url "${url}/search?q=\"${args}\"&sort=${category}&pagesize=${SURFRAW_stack_results}"
	else
	    w3_browse_url "${url}/search?q=\"${args}\""
	fi
fi
