#!/bin/bash

if [ -z "$1" ];
then
    echo "no dir arg"
    exit 3
fi
dest="$1"

while ls $HOME/Downloads/*.crdownload; do
    sleep 2;
done

mkdir -p $dest
cp $HOME/Downloads/*.mp3 $dest
ls -l $dest

