#!/bin/sh
# set -e
set  -x
# set -v
wordnet $1 -over -synsn -synsv -synsa -synsr -simsv -antsn -antsv -antsa -antsr -famln -famlv -famla -famlr -hypen -hypev -hypon -hypov -treen -treev -coorn -coorv -derin -deriv -domnn -domnv -domna -domnr -domtn -domtv -domta -domtr -subsn -partn -membn -meron -hmern -sprtn -smemn -ssubn -holon -hholn -entav -framv -causv -perta -pertr -attrn -attra > /tmp/worddes

# emacsclient -nw  -c -a "" /tmp/worddes
less /tmp/worddes
